version: '3.5'

services:
  keycloak:
    build: .

    environment:
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://db/keycloak"
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: change_me   

    command: "start-dev --import-realm"
    ports: 
      - "8443:8443"
    depends_on:
      - db
    volumes:
      - ./realms:/opt/keycloak/data/import

  db:
    container_name: keycloak_postgres
    image: postgres
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432"
    restart: unless-stopped

volumes:
  postgres:

